FROM ubuntu:22.04
WORKDIR /app
RUN apt update
COPY requirements.txt .
RUN apt install -y python3 python3-pip
RUN pip3 install -r requirements.txt

COPY ./src .

EXPOSE 8501
CMD ["streamlit", "run", "Home.py"]